version: v2beta1
name: devspace-application

images:
  # By default ./Dockerfile will be used
  app:
    image: ${REGISTRY}/${NAMESPACE}/${IMAGE}
    #image: registry.7xqfswmw24tga222.ertia.cloud/demo/${IMAGE}
    tags:
      - ${IMAGE_TAG}
      # This will be replaced during build time with
      # something like dev-ads13as1-sA4ve. Each hashtag
      # represents a random character.
      - dev-${devspace.git.commit}-##### 
    rebuildStrategy: ignoreContextChanges
    createPullSecret: true
    kaniko:
      insecure: true
      #serviceAccount: kaniko-builder
      pullSecret: devspace-pull-secrets
      additionalMounts:
      - mountPath: /kaniko/.docker/
        secret:
          name: devspace-pull-secrets
          items:
          - key: .dockerconfigjson
            path: config.json
      args:
      - --skip-tls-verify
      - --skip-tls-verify-pull
      - --cache-dir=/tmp
      - --verbosity=debug

deployments:
  helmdeploy:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: ${REGISTRY}/${NAMESPACE}/${IMAGE}
          # - image: registry.7xhg4dhk249nu222.ertia.cloud/demo/${IMAGE}
        service:
          ports: 
            - port: 8080
              containerPort: 80

pullSecrets:
  harbor:
    registry: ${REGISTRY} #registry.7xhg4dhk249nu222.ertia.cloud
    secret: devspace-pull-secrets
    serviceAccounts: 
      - kaniko-builder
      - default

pipelines:
  deploy: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all -t $(git describe --always)
    create_deployments --all  

localRegistry:
  enabled: false

vars:
- name: IMAGE
  source: env
- name: REGISTRY
  source: env
- name: NAMESPACE
  source: env
  default: "apps"
- name: IMAGE_TAG
  source: env
