version: v2beta1
name: sample-golang

images:
  # By default ./Dockerfile will be used
  app:
    image: registry-harbor-registry.registry:5000/${IMAGE}
    tags:
      - ${IMAGE_TAG}
    rebuildStrategy: ignoreContextChanges
    createPullSecret: true
    kaniko:
      insecure: true
      #serviceAccount: kaniko-builder
      pullSecret: devspace-pull-secrets
      additionalMounts:
      - mountPath: /kaniko/.docker/
        secret:
          name: devspace-pull-secrets
          items:
          - key: .dockerconfigjson
            path: config.json
      args:
      - --skip-tls-verify
      - --skip-tls-verify-pull
      - --cache-dir=/tmp
      - --verbosity=debug

deployments:
  helmdeploy:
    helm:
      values:
        containers:
          - image: registry-harbor-registry.registry:5000/${IMAGE}

pullSecrets:
  harbor:
    registry: registry-harbor-registry.registry:5000
    secret: devspace-pull-secrets
    serviceAccounts: 
      - kaniko-builder
      - default

pipelines:
  deploy: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all  
    # extend the default deploy pipeline
    #install_go_dependencies
    #install_crds

localRegistry:
  enabled: false

vars:
  IMAGE: sample-golang
  IMAGE_TAG: latest


#dev:
#  my-dev:
#    imageSelector: ${IMAGE}
#    terminal: {}
#    ports:
 #   - port: 8080
 #   sync:
 #   - path: ./
