apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: ertia-registry-cache
registries:
  create:
    name: docker-io # name of the registry container
    proxy:
      remoteURL: https://registry-1.docker.io # proxy DockerHub
    volumes:
      - /tmp/reg:/var/lib/registry # persist data locally in /tmp/reg
  config: | # tell K3s to use this registry when pulling from DockerHub
    mirrors:
      "docker.io":
        endpoint:
          - http://docker-io:5000
