apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    namespace: tekton-pipelines
    dockerConfig:
      secretName: registry-docker-config
    serviceAccount: kaniko-builder
  artifacts:
  - image: registry-harbor-registry.registry:5000/sample-golang
    kaniko:
      buildContext:
        localDir: {}
      dockerfile: ./.ertia/deploy/Dockerfile
      cache: {}
      insecure: true
      insecurePull: true
      #cleanup: true


deploy:
  docker:
    images:
    - registry-harbor-registry.registry:5000/sample-golang

manifests:
  rawYaml:
  - k8s/**
