apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-golang
build:
  cluster:
    namespace: tekton-pipelines
    dockerConfig:
      secretName: tekton-docker-config
    serviceAccount: kaniko-builder
  artifacts:
  - image: registry-harbor-registry.registry:5000/sample-golang
    kaniko:
      buildContext:
        localDir: {}
      dockerfile: ./Dockerfile
      cache: {}
      insecure: true
      insecurePull: true
      insecureRegistry: ["registry-harbor-registry.registry:5000", "registry-harbor-registry.registry"]
      cleanup: true
      skipTLS: true
      skipTLSVerifyPull: true

  insecureRegistries: ["registry-harbor-registry.registry:5000", "registry-harbor-registry.registry"]

#deploy:
#  kubectl: 
#    defaultNamespace: default

manifests:
  rawYaml:
  - k8s/**
